### ISSUE TITLE
MacOs Build Issues

### ISSUE THREAD

**Issue by kragall** [google/heir#1797]
So I've got a new Mac and while setting up heir there I ran into build problems. After spending some time there it turns out that even with my old Mac (where the build environment was working previously) I'm not able to build heir anymore. I'm not sure, when it broke exactly.

The three errors I get all seem to occur in macOS sdk files:
```
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/stdio.h:61:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/_stdio.h:318:7: error: expected identifier or '('
  318 | FILE    *fdopen(int, const char *) __DARWIN_ALIAS_STARTING(__MAC_10_6, __IPHONE_2_0, __DARWIN_ALIAS(fdopen));
      |          ^

usr/include/stdio.h:61:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/_stdio.h:318:7: error: expected ')'

In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/stdio.h:61:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/_stdio.h:318:7: error: expected ')'
  318 | FILE    *fdopen(int, const char *) __DARWIN_ALIAS_STARTING(__MAC_10_6, __IPHONE_2_0, __DARWIN_ALIAS(fdopen));
      |          ^
external/net_zlib/zutil.h:140:33: note: expanded from macro 'fdopen'
  140 | #        define fdopen(fd,mode) NULL /* No fdopen() */
      |

In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/stdio.h:61:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/_stdio.h:318:7: error: expected ')'
  318 | FILE    *fdopen(int, const char *) __DARWIN_ALIAS_STARTING(__MAC_10_6, __IPHONE_2_0, __DARWIN_ALIAS(fdopen));
      |          ^
external/net_zlib/zutil.h:140:33: note: expanded from macro 'fdopen'
  140 | #        define fdopen(fd,mode) NULL /* No fdopen() */
      |                                 ^
```

To me it looks like `fdopen` is defined both in the macOS sdk and in `zutil.h` and this somehow causes the build problem. But I have no idea how to fix this. Is the macOs build pipeline not affected by this?

**Comment by asraa** [comment]
Ah! Sorry I can't help debug too much since I don't have a MacOS - but... given that it's not working on your old mac... could you try
```
bazel clean --expunge
``` 
and retry the build if you haven't already?

**Comment by AlexanderViand** [comment]
Probably unrelated, but current `main` does not build on mac os CI either, but with very different error:
https://github.com/google/heir/actions/runs/14892141822/job/41826547925?pr=1799

**Comment by kragall** [comment]
So we managed a workaround to get the build going again by disabling yosys, i.e. with the following command I'm able to build heir:

`bazel build @heir//tools:heir-opt --//:enable_yosys=false`

I'm on macOS 15.4 with Xcode 16.3 and the cause of the error seems to be that in net_zlib there's a check if `fdopen` is defined and if it's not defined it defines it. The problem is that `fdopen` is defined as a macro in some file of the sdk and the macro is not an object that can be checked with `ifndef`. 

This means that this dependency loaded in WORKSPACE.bzlmod causes the issue:
`load("@rules_hdl//dependency_support/net_zlib:net_zlib.bzl", "net_zlib")`

Apparently, this net_zlib doesn't compile on macOS 15.4, but it's only a dependency of yosys.

**Comment by j2kun** [comment]
> Probably unrelated, but current `main` does not build on mac os CI either, but with very different error: https://github.com/google/heir/actions/runs/14892141822/job/41826547925?pr=1799

I tracked down the issue to soplex using DEBUG as a variable name when OSX system headers expect it as a preprocessor definition: https://github.com/scipopt/soplex/issues/47

I'm not sure we have a good solution to this except to run with `-c opt` on OSX, and to try to get an upstream fix merged.

**Comment by j2kun** [comment]
Back to the main build failure, it looks like upstream zlib removed the fdopen defines in [4bd9a71f3539b5ce47f0c67ab5e01f3196dc8ef9](https://github.com/madler/zlib/commit/4bd9a71f3539b5ce47f0c67ab5e01f3196dc8ef9)

I will try bumping the version

**Comment by kragall** [comment]
So #1878 solves this issue, but the build still fails, this time with:
```
ERROR: /private/var/tmp/_bazel_mar69689/0d09f61371de8add9eab1921e8302ffb/external/org_sourceware_libffi/BUILD.bazel:107:11: Compiling src/aarch64/sysv.S failed: (Exit 1): wrapped_clang failed: error executing CppCompile command (from target @@org_sourceware_libffi//:libffi)
  (cd /private/var/tmp/_bazel_mar69689/0d09f61371de8add9eab1921e8302ffb/sandbox/darwin-sandbox/1863/execroot/_main && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=15.4 \
    BAZEL_CXXOPTS='-std=c++17' \
    CC=clang \
    CXX=clang++ \
    PATH=/bin:/usr/bin:/usr/local/bin \
    XCODE_VERSION_OVERRIDE=16.3.0.16E140 \
  bazel-out/darwin_arm64-opt-exec-ST-d57f47055a04/bin/external/apple_support+/crosstool/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g '-fdebug-prefix-map=__BAZEL_EXECUTION_ROOT__=.' '-fdebug-prefix-map=__BAZEL_XCODE_DEVELOPER_DIR__=/PLACEHOLDER_DEVELOPER_DIR' -iquote external/org_sourceware_libffi -iquote bazel-out/darwin_arm64-dbg/bin/external/org_sourceware_libffi -isystem external/org_sourceware_libffi/generated -isystem bazel-out/darwin_arm64-dbg/bin/external/org_sourceware_libffi/generated -isystem external/org_sourceware_libffi/include -isystem bazel-out/darwin_arm64-dbg/bin/external/org_sourceware_libffi/include -isystem external/org_sourceware_libffi/generated/include_aarch64 -isystem bazel-out/darwin_arm64-dbg/bin/external/org_sourceware_libffi/generated/include_aarch64 -MD -MF bazel-out/darwin_arm64-dbg/bin/external/org_sourceware_libffi/_objs/libffi/sysv.d '-DHAVE_ALLOCA_H=1' '-DHAVE_AS_CFI_PSEUDO_OP=1' '-DHAVE_HIDDEN_VISIBILITY_ATTRIBUTE=1' '-DHAVE_STDIO_H=1' '-DHAVE_STDLIB_H=1' '-DHAVE_STRING_H=1' '-DHAVE_INTTYPES_H=1' '-DHAVE_STDINT_H=1' '-DHAVE_STRINGS_H=1' '-DHAVE_SYS_STAT_H=1' '-DHAVE_SYS_TYPES_H=1' '-DHAVE_UNISTD_H=1' '-DSTDC_HEADERS=1' '-DHAVE_DLFCN_H=1' '-DSIZEOF_SIZE_T=8' '-DHAVE_MEMCPY=1' '-DSIZEOF_DOUBLE=8' '-DSIZEOF_LONG_DOUBLE=8' '-DSYMBOL_UNDERSCORE=1' '-DFFI_EXEC_TRAMPOLINE_TABLE=1' '-DHAVE_RO_EH_FRAME=1' '-DEH_FRAME_FLAGS=a' '-DFFI_GO_CLOSURES=1' -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/MacOSX.platform/Developer/Library/Frameworks -no-canonical-prefixes -pthread '-fdiagnostics-color=always' -Wno-deprecated-declarations -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -target arm64-apple-macosx15.4 -c external/org_sourceware_libffi/src/aarch64/sysv.S -o bazel-out/darwin_arm64-dbg/bin/external/org_sourceware_libffi/_objs/libffi/sysv.o)
# Configuration: 7d1b94bc18ef2a699fc65b83eacbd7eee4e1a8b4a3d0ca90d254e29e5e5902f3
# Execution platform: @@platforms//host:host

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
/var/folders/z4/1bj3rn2n68bc6qj_ftqgwfgh0000gp/T/sysv-521d30.s:28:2: error: invalid CFI advance_loc expression
 .cfi_def_cfa x1, 40;
 ^
/var/folders/z4/1bj3rn2n68bc6qj_ftqgwfgh0000gp/T/sysv-521d30.s:255:2: error: invalid CFI advance_loc expression
 .cfi_adjust_cfa_offset (8*2 + (8 * 16 + 8 * 8) + 64)
 ^
/var/folders/z4/1bj3rn2n68bc6qj_ftqgwfgh0000gp/T/sysv-521d30.s:469:2: error: invalid CFI advance_loc expression
 .cfi_adjust_cfa_offset (8*2 + (8 * 16 + 8 * 8) + 64)
 ^
```

This seems to be a known issue in libffi and was fixed in a recent version (https://github.com/libffi/libffi/issues/852)
